### ISSUE TITLE
plump_helmet_grow_time may not be correct

### ISSUE THREAD

**Issue by LeafyLappa** [FaceDeer/dfcaverns#18]
There seems to be a typo in how plump_helmet_grow_time is calculated in this line in [plump_helmet.lua](../tree/master/df_farming/plump_helmet.lua):

```LUA
local plump_helmet_grow_time = df_farming.config.plant_growth_time * df_farming.config.cave_wheat_delay_multiplier / 4
```

Quick comparison against other plants suggests `plump_helmet_delay_multiplier` should be there and not `cave_wheat_delay_multiplier`.

**Comment by FaceDeer** [comment]
Quite right, thanks for catching that.
