### ISSUE TITLE
Crashes with 5.5.0 before opening

### ISSUE THREAD

**Issue by 3raven** [FaceDeer/dfcaverns#23]
Hi,
I upgraded to 5.5.0 recently and with this mod it crashes at opening with the following error message 

ModError: Failed to load and run script from /home/moi/.minetest/mods/dfcaverns/df_caverns/init.lua:
/home/moi/.minetest/mods/dfcaverns/df_caverns/level1.lua:297: attempt to call field 'register_layer' (a nil value)
stack traceback:
	/home/moi/.minetest/mods/dfcaverns/df_caverns/level1.lua:297: in main chunk
	[C]: in function 'dofile'
	/home/moi/.minetest/mods/dfcaverns/df_caverns/init.lua:13: in main chunk

**Comment by FaceDeer** [comment]
When I got set back up to do some modding again I actually managed to reproduce crash-on-open behaviour, though not exactly as you described above. There were all kinds of things glitchy with Minetest - mapgen wasn't placing any soil or plants even with no mods at all added to the base minetest game. I don't know what the exact cause was, but it had something to do with how I was updating versions of Minetest - when I wiped everything completely instead up trying to upgrade old versions all the problems went away.

Might that be a similar situation to what you were having?

**Comment by 3raven** [comment]
I dont remenber exactly but it seems that it happened only after the update and seem caused by it.

**Comment by FaceDeer** [comment]
Okay, I'm going to file this as "just one of those things" in that case.

Sorry it took so long to get back to this, I took a break from modding and just sort of went on to other things. I'm starting to get the creative yen back now, though.
