### ISSUE TITLE
Could give this mod support for Mineclone 5?

### ISSUE THREAD

**Issue by SamuelBucher** [FaceDeer/dfcaverns#24]
I'm very impressed by this wonderful mod's cave generation, but it's a real shame that it only works with the default game. Could give it support for Mineclone 5?

**Comment by FaceDeer** [comment]
I actually started doing some work to pry this mod away from depending on the "default" mod a while back, with Mineclone support specifically in mind. If you look through the various sub-mods this modpack is composed of you'll find a bunch of files called "dependencies.lua", what I was doing was basically trying to gather up all of the references to default mod code and resources into those specific places. There were a bunch of things that there were no Mineclone equivalents for, as I recall, so I stopped short of actually adding that support. But the framework is there for some continued work in that direction.

I just got a whole bunch of issues filed that I'm going to work on first (I've been retired from Minetest modding for a couple years so I'm feeling rusty, those will be good to get back in practice) but I can resume poking at Mineclone a bit more after I'm done those. I assume Mineclone's continued its own development so maybe some of those things that were missing last time have some equivalents in place now.

**Comment by MaximKhannanov** [comment]
Thank you for your response. Do what you think is best.

**Comment by FaceDeer** [comment]
Alright, I've begun poking around a bit with Mineclone 2/5. It seems a lot of DF stuff should be fairly easy to make compatible with its core mods, except for one really glaring thing; both of these games have bedrock at just -64 meters. There's a "nether" realm  way down deep below that (looks like I may need to rename nethercaps when Mineclone is being used to avoid some confusion there) but I don't see any obvious settings for adding the sort of depth that's needed for DF Caverns' content to exist in. Do you know how to go about lowering the bedrock's altitude?

**Comment by SamuelBucher** [comment]
I'm afraid I know nothing about Minetest modding or Lua. My best guess is to look into Mineclone's code, find where it sets bedrock height, and modify that. But I'm speaking from whatever little experience with modding I have, such approach might not even be valid for Minetest.

**Comment by FaceDeer** [comment]
I've made some progress. I was able to get Mineclone 2 to load with df_caverns installed, though I didn't actually visit any caverns yet - I was crashing with mapgen OOM errors from Mineclone when I tried, I might need to do something fancy to get Mineclone 2 to not try doing mapgen work there.

Mineclone 5, on the other hand, may be a bigger problem. They actually null out minetest.register_on_generated, which prevents other non-Mineclone mapgens from running at all. It looks like this might be a result of a bug in their code, I think I'll need to file an issue with them and see what happens. But as the code currently exists I may not be able to so easily plug DF_Caverns into Mineclone 5.

No promises on timelines here.

If nothing else, this has given me some opportunity to clean up areas of df_caverns code I haven't touched in a long time.

**Comment by FaceDeer** [comment]
I've also found that Mineclone 5's "mcl_worlds.is_in_void" method, which teleports or kills the player if they go below the bedrock, is written and used in a manner that makes it impossible to override or reconfigure from the outside. That'll be another issue to file to the Mineclone 5 people.

**Comment by FaceDeer** [comment]
For reference, [the issue I've filed with Mineclone 5 about this](https://git.minetest.land/MineClone5/MineClone5/issues/399)

**Comment by FaceDeer** [comment]
An update: I think I've now finished the main work of changing DFCaverns to be able to run equally well on Minetest Game (and many of its derivatives) and Mineclone 5. The only thing left on my to-do list is to play around with the effects of explosives, the things that are supposed to go bang still go bang but the scale and effects of the bang are different using Mineclone's code. [You need this branch of Mineclone 5 for it to work](https://git.minetest.land/FaceDeer/MineClone5/src/branch/mapgen_mod_compatibility), once I've tested more thoroughly I'll submit a pull request.

I haven't tested this out on Mineclone 2 in any significant way yet.

[Here's the branch of DFCaverns with Mineclone support to go along with that](https://github.com/FaceDeer/dfcaverns/tree/mineclone_compatibility). At this point testing is the biggest remaining task, and that's something anyone can help with. :)

**Comment by FaceDeer** [comment]
The update I released for dfcaverns should work with Mineclone 5 once [this pull request](https://git.minetest.land/MineClone5/MineClone5/pulls/409) has been accepted.

**Comment by FaceDeer** [comment]
Mineclone5 merged my pull request so I'm going to close this issue now.
