### ISSUE TITLE
Certain trees destroy blocks around their base when grown

### ISSUE THREAD

**Issue by alerikaisattera** [FaceDeer/dfcaverns#27]
When growing from saplings, Tower Caps, Black Caps, Nether Caps and possibly few other trees dectroy a few blocks around their base

**Comment by FaceDeer** [comment]
Neat, this one's actually a subterrane bug. The generic "build giant mushroom" helper function from there wasn't checking if the nodes directly below the sapling were buildable before putting stem there.
