### ISSUE TITLE
Jungle grass and Primordial mycelium do not spread

### ISSUE THREAD

**Issue by alerikaisattera** [FaceDeer/dfcaverns#35]
Jungle grass and Primordial mycelium do not spread to adjacent dirt nodes. Seems to be caused by errors in ABM: they use `"df_mapitems:dirt_with_jungle_grass"` and `"df_mapitems:dirt_with_mycelium"` instead of correct `"df_primordial_items:dirt_with_jungle_grass"` and `"df_primordial_items:dirt_with_mycelium"`

**Comment by FaceDeer** [comment]
Thanks! That's likely a copy and paste error from years ago. :)

**Comment by FaceDeer** [comment]
Should be working now.
